management:
  endpoints:
    web:
      exposure:
        include: info, refresh, keepalive, health
logging:
  level:
    org.springframework.cloud.kubernetes: DEBUG

spring:
  application:
    name: mila-configmap-demo

server:
  port: 8085